/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.13.0+p3-g40b6564e
 *
 * Project: 'app.release+DevKit-E8-HP' 
 * Target:  'release+DevKit-E8-HP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* ARM::RTOS&FreeRTOS:Config&FreeRTOS@11.2.0 */
#define RTE_RTOS_FreeRTOS_CONFIG        /* RTOS FreeRTOS Config for FreeRTOS API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.2.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@11.2.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.2.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@11.2.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* AlifSemiconductor::BSP:External peripherals:ILI9806E LCD panel@2.1.0 */
#define RTE_Drivers_MIPI_DSI_ILI9806E_PANEL    /* Driver ILI9806E LCD panel*/
/* AlifSemiconductor::CMSIS Driver:USART@2.1.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:CDC@2.1.0 */
#define RTE_Drivers_CDC200                 /* Driver CDC200*/
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.1.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI CSI2 DPHY@2.1.0 */
#define RTE_Drivers_MIPI_DSI_CSI2_DPHY   /* Driver DPHY */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI@2.1.0 */
#define RTE_Drivers_MIPI_DSI               /* Driver MIPI DSI */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.1.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Graphics:Acceleration:GPU AlifSemi-Dave2D@1.2.0 */
/*! \brief enable Dave2D */
#define LV_USE_DRAW_DAVE2D  1
/* LVGL::LVGL&LVGL9:Demos:Benchmark@9.5.0 */
/*! \brief enable demo:benchmark */
#define LV_USE_DEMO_BENCHMARK           1
/* LVGL::LVGL&LVGL9:Demos:Widgets@9.5.0 */
/*! \brief enable demo:widgets support */
#define LV_USE_DEMO_WIDGETS             1
/* LVGL::LVGL&LVGL9:Essential@9.5.0 */
/*! \brief Enable LVGL */
#define RTE_GRAPHICS_LVGL
/* LVGL::LVGL&LVGL9:OS Abstraction Layer&FreeRTOS@9.5.0 */
#define LV_USE_OS   LV_OS_FREERTOS


#endif /* RTE_COMPONENTS_H */
